import { DEMO } from "./constants";
import type {
	AppLocale,
	EndpointCopy,
	EndpointDefinition,
	LocalizedCopy,
} from "./types";

type EndpointOptions = Partial<
	Pick<
		EndpointDefinition,
		"body" | "pathParams" | "query" | "destructive" | "special"
	>
>;

const copy = (
	enTitle: string,
	enDescription: string,
	deTitle: string,
	deDescription: string,
	trTitle: string,
	trDescription: string,
): EndpointCopy => ({
	en: { title: enTitle, description: enDescription },
	de: { title: deTitle, description: deDescription },
	tr: { title: trTitle, description: trDescription },
});

const endpoint = (
	id: string,
	method: EndpointDefinition["method"],
	path: string,
	endpointCopy: EndpointCopy,
	group: EndpointDefinition["group"],
	auth: EndpointDefinition["auth"],
	options: EndpointOptions = {},
): EndpointDefinition => ({
	id,
	method,
	path,
	copy: endpointCopy,
	group,
	auth,
	body: null,
	pathParams: [],
	query: [],
	destructive: false,
	special: null,
	...options,
});

export const ENDPOINTS: ReadonlyArray<EndpointDefinition> = [
	endpoint(
		"health-live",
		"GET",
		"/health/live",
		copy(
			"Liveness check",
			"A lightweight, database-independent process probe.",
			"Liveness prüfen",
			"Leichter, datenbankunabhängiger Prozess-Probe.",
			"Liveness kontrolü",
			"İşlem ayakta mı? Veritabanından bağımsız, hafif probe.",
		),
		"operations",
		"public",
	),
	endpoint(
		"health-ready",
		"GET",
		"/health/ready",
		copy(
			"Readiness check",
			"Checks whether the API and PostgreSQL are ready for traffic.",
			"Readiness prüfen",
			"Prüft, ob API und PostgreSQL für Traffic bereit sind.",
			"Readiness kontrolü",
			"API ve PostgreSQL trafiğe hazır mı?",
		),
		"operations",
		"public",
	),
	endpoint(
		"jwks",
		"GET",
		"/.well-known/jwks.json",
		copy(
			"Public signing keys",
			"Returns active and retiring ES256 keys in JWKS format.",
			"Öffentliche Signaturschlüssel",
			"Liefert aktive und auslaufende ES256-Schlüssel im JWKS-Format.",
			"Public signing keys",
			"Aktif ve retiring ES256 anahtarlarını JWKS biçiminde döndürür.",
		),
		"operations",
		"public",
	),

	endpoint(
		"auth-register",
		"POST",
		"/api/v1/auth/register",
		copy(
			"Register an account",
			"Creates an account and sends a verification email to Mailpit.",
			"Konto registrieren",
			"Erstellt ein Konto und sendet eine Bestätigungsmail an Mailpit.",
			"Yeni hesap kaydı",
			"Hesabı oluşturur ve Mailpit'e doğrulama e-postası yollar.",
		),
		"authentication",
		"public",
		{
			body: {
				email: "new-user@example.test",
				password: "V4lid!River-Stone-Cobalt-47",
				displayName: "New User",
			},
		},
	),
	endpoint(
		"auth-login",
		"POST",
		"/api/v1/auth/login",
		copy(
			"Sign in with email and password",
			"Starts a bearer or cookie session; returns a ticket when MFA is enabled.",
			"Mit E-Mail und Passwort anmelden",
			"Startet eine Bearer- oder Cookie-Sitzung; bei MFA wird ein Ticket geliefert.",
			"E-posta ve parola ile giriş",
			"Bearer/body ya da cookie taşımasıyla yeni oturum açar; MFA etkinse ticket döndürür.",
		),
		"authentication",
		"public",
		{ body: { email: DEMO.user.email, password: DEMO.user.password } },
	),
	endpoint(
		"auth-login-mfa",
		"POST",
		"/api/v1/auth/login/mfa",
		copy(
			"Complete MFA sign-in",
			"Completes the password ticket with TOTP or a recovery code.",
			"MFA-Anmeldung abschließen",
			"Schließt das Passwort-Ticket mit TOTP oder Recovery-Code ab.",
			"MFA girişini tamamla",
			"Parola adımından gelen ticket'ı TOTP veya recovery code ile tamamlar.",
		),
		"authentication",
		"public",
		{ body: { mfaTicket: "{{mfaTicket}}", code: "{{totpCode}}" } },
	),
	endpoint(
		"auth-refresh",
		"POST",
		"/api/v1/auth/refresh",
		copy(
			"Refresh the token pair",
			"Rotates the refresh token atomically and revokes the session on reuse.",
			"Token-Paar erneuern",
			"Rotiert das Refresh-Token atomar und widerruft die Sitzung bei Wiederverwendung.",
			"Token çiftini yenile",
			"Refresh token'ı atomik olarak döndürür; eski token'ın tekrar kullanımı oturumu iptal eder.",
		),
		"authentication",
		"public",
		{ body: { refreshToken: "{{refreshToken}}" } },
	),
	endpoint(
		"auth-logout",
		"POST",
		"/api/v1/auth/logout",
		copy(
			"End the active session",
			"Revokes the current session and clears authentication cookies.",
			"Aktive Sitzung beenden",
			"Widerruft die aktuelle Sitzung und löscht Auth-Cookies.",
			"Aktif oturumu kapat",
			"Geçerli oturumu iptal eder ve varsa auth cookie'lerini temizler.",
		),
		"authentication",
		"auth",
		{ destructive: true },
	),
	endpoint(
		"auth-csrf",
		"GET",
		"/api/v1/auth/csrf",
		copy(
			"Create a CSRF token",
			"Creates a session-bound double-submit token for cookie mutations.",
			"CSRF-Token erzeugen",
			"Erzeugt ein sitzungsgebundenes Double-Submit-Token für Cookie-Mutationen.",
			"CSRF token üret",
			"Cookie taşımasındaki mutasyonlar için oturuma bağlı double-submit token üretir.",
		),
		"authentication",
		"auth",
	),
	endpoint(
		"social-authorize",
		"GET",
		"/api/v1/auth/social/{provider}/authorize",
		copy(
			"Start social sign-in",
			"Returns a local fixture URL in Development or a real provider URL elsewhere.",
			"Social Login starten",
			"Liefert in Development eine Fixture-URL, sonst die echte Provider-URL.",
			"Sosyal girişi başlat",
			"Development'ta yerel fixture URL'si; diğer ortamlarda gerçek sağlayıcı authorize URL'si döner.",
		),
		"authentication",
		"public",
		{
			pathParams: [{ name: "provider", value: "google" }],
			special: "social",
		},
	),
	endpoint(
		"social-callback",
		"GET",
		"/api/v1/auth/social/{provider}/callback",
		copy(
			"Complete social sign-in",
			"Consumes signed state, maps the provider identity, and starts a session.",
			"Social Login abschließen",
			"Verbraucht signierten State, ordnet die Provider-Identität zu und startet eine Sitzung.",
			"Sosyal giriş callback",
			"İmzalı state'i tüketir, sağlayıcı kimliğini yerel hesaba dönüştürür ve oturum açar.",
		),
		"authentication",
		"public",
		{
			pathParams: [{ name: "provider", value: "google" }],
			query: [
				{ name: "code", value: "{{socialCode}}" },
				{ name: "state", value: "{{socialState}}" },
				{ name: "error", value: "" },
			],
		},
	),
	endpoint(
		"email-send",
		"POST",
		"/api/v1/email-verification/send",
		copy(
			"Resend verification email",
			"Sends the active user's verification link to the local Mailpit inbox.",
			"Bestätigungsmail erneut senden",
			"Sendet den Bestätigungslink des aktiven Benutzers an Mailpit.",
			"Doğrulama e-postasını yeniden gönder",
			"Aktif kullanıcının doğrulama bağlantısını yerel Mailpit inbox'ına yollar.",
		),
		"authentication",
		"auth",
	),
	endpoint(
		"email-confirm",
		"POST",
		"/api/v1/email-verification/confirm",
		copy(
			"Verify the email address",
			"Consumes the one-time verification token from the Mailpit message.",
			"E-Mail-Adresse bestätigen",
			"Verbraucht das einmalige Bestätigungstoken aus Mailpit.",
			"E-posta adresini doğrula",
			"Mailpit mesajındaki tek kullanımlık doğrulama token'ını tüketir.",
		),
		"authentication",
		"public",
		{ body: { token: "{{verificationToken}}" } },
	),
	endpoint(
		"password-request",
		"POST",
		"/api/v1/password-reset/request",
		copy(
			"Request a password reset",
			"Sends a reset link to Mailpit without revealing account existence.",
			"Passwort-Reset anfordern",
			"Sendet einen Reset-Link an Mailpit, ohne die Existenz des Kontos offenzulegen.",
			"Parola sıfırlama iste",
			"Hesap varlığını açığa çıkarmadan Mailpit'e sıfırlama bağlantısı yollar.",
		),
		"authentication",
		"public",
		{ body: { email: DEMO.user.email } },
	),
	endpoint(
		"password-confirm",
		"POST",
		"/api/v1/password-reset/confirm",
		copy(
			"Save a new password",
			"Consumes the token, rotates the security stamp, and revokes every session.",
			"Neues Passwort speichern",
			"Verbraucht das Token, rotiert den Security Stamp und widerruft alle Sitzungen.",
			"Yeni parolayı kaydet",
			"Tek kullanımlık token'ı tüketir, security stamp'i döndürür ve tüm oturumları iptal eder.",
		),
		"authentication",
		"public",
		{
			body: {
				token: "{{passwordResetToken}}",
				newPassword: "N3w!River-Stone-Cobalt-82",
			},
			destructive: true,
		},
	),

	endpoint(
		"users-me",
		"GET",
		"/api/v1/users/me",
		copy(
			"Get my profile",
			"Resolves identity from the token subject and returns roles and security posture.",
			"Mein Profil abrufen",
			"Löst die Identität aus dem Token-Subject auf und liefert Rollen und Sicherheitsstatus.",
			"Profilimi getir",
			"Kimliği token'daki subject'ten çözer; roller ve güvenlik duruşunu döndürür.",
		),
		"account",
		"auth",
	),
	endpoint(
		"users-update",
		"PATCH",
		"/api/v1/users/me",
		copy(
			"Update my profile",
			"Updates only the display name.",
			"Mein Profil aktualisieren",
			"Aktualisiert ausschließlich den Anzeigenamen.",
			"Profilimi güncelle",
			"Yalnızca display name alanını günceller.",
		),
		"account",
		"auth",
		{ body: { displayName: "Workbench User" } },
	),
	endpoint(
		"users-delete",
		"DELETE",
		"/api/v1/users/me",
		copy(
			"Delete my account",
			"Irreversibly deletes the account and credentials; requires recent sign-in.",
			"Mein Konto löschen",
			"Löscht Konto und Zugangsdaten endgültig; aktuelle Anmeldung erforderlich.",
			"Hesabımı sil",
			"Hesabı ve tüm kimlik bilgilerini geri alınamaz biçimde siler; yakın zamanda giriş gerekir.",
		),
		"account",
		"recent",
		{ destructive: true },
	),
	endpoint(
		"users-password",
		"PUT",
		"/api/v1/users/me/password",
		copy(
			"Change my password",
			"Verifies the current password and revokes sibling sessions.",
			"Mein Passwort ändern",
			"Prüft das aktuelle Passwort und widerruft parallele Sitzungen.",
			"Parolamı değiştir",
			"Mevcut parolayı doğrular, kardeş oturumları iptal eder.",
		),
		"account",
		"auth",
		{
			body: {
				currentPassword: DEMO.user.password,
				newPassword: "N3w!River-Stone-Cobalt-82",
			},
			destructive: true,
		},
	),
	endpoint(
		"users-accounts",
		"GET",
		"/api/v1/users/me/accounts",
		copy(
			"List linked accounts",
			"Returns local IDs and provider data for Google and GitHub links.",
			"Verknüpfte Konten auflisten",
			"Liefert lokale IDs und Provider-Daten für Google- und GitHub-Verknüpfungen.",
			"Bağlı hesapları listele",
			"Google/GitHub bağlantılarının yerel id ve provider bilgisini döndürür.",
		),
		"account",
		"auth",
	),
	endpoint(
		"users-unlink",
		"DELETE",
		"/api/v1/users/me/accounts/{accountId}",
		copy(
			"Unlink a social account",
			"Prevents removing the last available sign-in method.",
			"Social-Konto trennen",
			"Verhindert das Entfernen der letzten Anmeldemethode.",
			"Sosyal hesabı ayır",
			"Son giriş yöntemini kaldırmaya izin vermez.",
		),
		"account",
		"auth",
		{
			pathParams: [{ name: "accountId", value: DEMO.accountId }],
			destructive: true,
		},
	),

	endpoint(
		"sessions-list",
		"GET",
		"/api/v1/sessions",
		copy(
			"List my sessions",
			"Shows two fixture sessions and sessions created by sign-in.",
			"Meine Sitzungen auflisten",
			"Zeigt zwei Fixture-Sitzungen und durch Anmeldung erzeugte Sitzungen.",
			"Oturumlarımı listele",
			"Hazır iki fixture oturumu ve girişle oluşan güncel oturumu gösterir.",
		),
		"sessions",
		"auth",
	),
	endpoint(
		"sessions-revoke",
		"DELETE",
		"/api/v1/sessions/{sessionId}",
		copy(
			"Revoke a session",
			"Searches only within the caller's sessions; foreign IDs return 404.",
			"Sitzung widerrufen",
			"Sucht nur in den Sitzungen des Aufrufers; fremde IDs liefern 404.",
			"Bir oturumu iptal et",
			"Yalnızca çağıranın oturum uzayında arar; diğer kullanıcı id'leri 404 döner.",
		),
		"sessions",
		"auth",
		{
			pathParams: [{ name: "sessionId", value: DEMO.sessionId }],
			destructive: true,
		},
	),
	endpoint(
		"sessions-revoke-others",
		"DELETE",
		"/api/v1/sessions",
		copy(
			"Revoke every other session",
			"Keeps the calling session and closes every other active session.",
			"Alle anderen Sitzungen widerrufen",
			"Behält die aufrufende Sitzung und schließt alle anderen aktiven Sitzungen.",
			"Diğer tüm oturumları iptal et",
			"İsteği yapan oturumu koruyup diğer aktif oturumları kapatır.",
		),
		"sessions",
		"auth",
		{ destructive: true },
	),

	endpoint(
		"mfa-enroll",
		"POST",
		"/api/v1/mfa/totp/enroll",
		copy(
			"Start TOTP enrollment",
			"Creates a Base32 secret and otpauth URI; the workbench calculates a live code.",
			"TOTP-Einrichtung starten",
			"Erzeugt Base32-Secret und otpauth-URI; die Workbench berechnet einen Live-Code.",
			"TOTP kaydını başlat",
			"Yeni Base32 secret ve otpauth URI üretir; workbench canlı kodu otomatik hesaplar.",
		),
		"security",
		"auth",
		{ special: "totp" },
	),
	endpoint(
		"mfa-confirm",
		"POST",
		"/api/v1/mfa/totp/confirm",
		copy(
			"Confirm TOTP enrollment",
			"Verifies the live code, enables MFA, and returns ten one-time recovery codes.",
			"TOTP-Einrichtung bestätigen",
			"Prüft den Live-Code, aktiviert MFA und liefert zehn einmalige Recovery-Codes.",
			"TOTP kaydını doğrula",
			"Canlı kodu doğrular, MFA'yı etkinleştirir ve 10 tek kullanımlık recovery code döndürür.",
		),
		"security",
		"auth",
		{ body: { code: "{{totpCode}}" }, special: "totp" },
	),
	endpoint(
		"mfa-disable",
		"DELETE",
		"/api/v1/mfa/totp",
		copy(
			"Disable TOTP",
			"Deletes the MFA credential and recovery codes after recent authentication.",
			"TOTP deaktivieren",
			"Löscht nach aktueller Authentifizierung MFA-Credential und Recovery-Codes.",
			"TOTP'yi kapat",
			"Yakın zamanda giriş şartıyla MFA credential ve recovery code'ları siler.",
		),
		"security",
		"recent",
		{ destructive: true },
	),
	endpoint(
		"mfa-recovery",
		"POST",
		"/api/v1/mfa/recovery-codes/regenerate",
		copy(
			"Regenerate recovery codes",
			"Invalidates the previous batch and returns new codes that are shown once.",
			"Recovery-Codes neu erzeugen",
			"Macht den alten Satz ungültig und liefert neue, einmal sichtbare Codes.",
			"Recovery code'ları yenile",
			"Önceki batch'i geçersiz kılar ve yalnızca bir kez gösterilen yeni kodlar döndürür.",
		),
		"security",
		"recent",
		{ destructive: true },
	),
	endpoint(
		"passkey-registration-options",
		"POST",
		"/api/v1/passkeys/registration/options",
		copy(
			"Create passkey registration options",
			"Stores a one-time challenge and returns WebAuthn creation options.",
			"Passkey-Registrierungsoptionen",
			"Speichert eine einmalige Challenge und liefert WebAuthn-Erstellungsoptionen.",
			"Passkey kayıt seçenekleri",
			"Sunucuda tek kullanımlık challenge saklar ve WebAuthn creation options döndürür.",
		),
		"security",
		"auth",
		{
			body: { label: "Workbench passkey" },
			special: "passkey-register",
		},
	),
	endpoint(
		"passkey-registration-complete",
		"POST",
		"/api/v1/passkeys/registration/complete",
		copy(
			"Complete passkey registration",
			"Verifies navigator.credentials.create() and stores the public credential.",
			"Passkey-Registrierung abschließen",
			"Prüft navigator.credentials.create() und speichert das öffentliche Credential.",
			"Passkey kaydını tamamla",
			"navigator.credentials.create() çıktısını doğrular ve public credential'ı kaydeder.",
		),
		"security",
		"auth",
		{
			body: { attestationResponse: {}, label: "Workbench passkey" },
		},
	),
	endpoint(
		"passkey-auth-options",
		"POST",
		"/api/v1/passkeys/authentication/options",
		copy(
			"Create passkey sign-in options",
			"Creates an anonymous WebAuthn assertion challenge.",
			"Passkey-Anmeldeoptionen",
			"Erzeugt eine anonyme WebAuthn-Assertion-Challenge.",
			"Passkey giriş seçenekleri",
			"Anonymous WebAuthn assertion challenge üretir.",
		),
		"security",
		"public",
		{ body: {}, special: "passkey-auth" },
	),
	endpoint(
		"passkey-auth-complete",
		"POST",
		"/api/v1/passkeys/authentication/complete",
		copy(
			"Sign in with a passkey",
			"Verifies the assertion signature and counter, then starts a session.",
			"Mit Passkey anmelden",
			"Prüft Assertion-Signatur und Zähler und startet eine Sitzung.",
			"Passkey ile giriş yap",
			"Assertion imzasını ve sayacını doğrular, yeni oturum açar.",
		),
		"security",
		"public",
		{ body: { assertionResponse: {} } },
	),
	endpoint(
		"passkeys-list",
		"GET",
		"/api/v1/passkeys",
		copy(
			"List passkeys",
			"Returns credential ID, label, and last use without key material.",
			"Passkeys auflisten",
			"Liefert Credential-ID, Bezeichnung und letzte Nutzung ohne Schlüsselmaterial.",
			"Passkey'leri listele",
			"Credential id, etiket ve son kullanım bilgisini döndürür; anahtar materyali taşımaz.",
		),
		"security",
		"auth",
	),
	endpoint(
		"passkey-delete",
		"DELETE",
		"/api/v1/passkeys/{credentialId}",
		copy(
			"Remove a passkey",
			"Deletes the Base64url credential ID within the caller's account.",
			"Passkey entfernen",
			"Löscht die Base64url-Credential-ID im Konto des Aufrufers.",
			"Passkey'i kaldır",
			"Base64url credential id'yi çağıran kullanıcı kapsamında siler.",
		),
		"security",
		"auth",
		{
			pathParams: [{ name: "credentialId", value: "{{credentialId}}" }],
			destructive: true,
		},
	),
	endpoint(
		"api-key-create",
		"POST",
		"/api/v1/api-keys",
		copy(
			"Create an API key",
			"Shows the secret once; scopes cannot exceed the user's permissions.",
			"API-Key erstellen",
			"Zeigt das Secret einmal; Scopes dürfen die Benutzerrechte nicht überschreiten.",
			"API key oluştur",
			"Secret'ı yalnızca bu yanıtta gösterir; kapsamlar kullanıcının izinlerini aşamaz.",
		),
		"security",
		"auth",
		{
			body: {
				name: "Local automation",
				scopes: ["users:read:any", "audit:read"],
				expiresAt: "2027-12-31T00:00:00Z",
			},
		},
	),
	endpoint(
		"api-keys-list",
		"GET",
		"/api/v1/api-keys",
		copy(
			"List API keys",
			"Returns prefix, scopes, use, and revocation data without secrets.",
			"API-Keys auflisten",
			"Liefert Prefix, Scopes, Nutzung und Widerruf ohne Secrets.",
			"API key'leri listele",
			"Secret olmadan prefix, kapsam, kullanım ve iptal bilgilerini döndürür.",
		),
		"security",
		"auth",
	),
	endpoint(
		"api-key-revoke",
		"DELETE",
		"/api/v1/api-keys/{keyId}",
		copy(
			"Revoke an API key",
			"Irreversibly revokes the credential while retaining its audit record.",
			"API-Key widerrufen",
			"Widerruft das Credential endgültig und behält den Audit-Datensatz.",
			"API key'i iptal et",
			"Credential'ı geri döndürülemez biçimde iptal eder; audit bağlantısı için satırı korur.",
		),
		"security",
		"auth",
		{
			pathParams: [{ name: "keyId", value: DEMO.apiKeyId }],
			destructive: true,
		},
	),

	endpoint(
		"admin-users-list",
		"GET",
		"/api/v1/admin/users",
		copy(
			"List users",
			"A paginated, searchable, and filterable administration view.",
			"Benutzer auflisten",
			"Paginierte, durchsuchbare und filterbare Administrationsansicht.",
			"Kullanıcıları listele",
			"Sayfalı, aranabilir, filtrelenebilir yönetim görünümü.",
		),
		"admin",
		"admin",
		{
			query: [
				{ name: "page", value: "1" },
				{ name: "pageSize", value: "20" },
				{ name: "sort", value: "createdAt:desc" },
				{ name: "search", value: "" },
				{ name: "role", value: "" },
				{ name: "emailVerified", value: "" },
				{ name: "locked", value: "" },
			],
		},
	),
	endpoint(
		"admin-user-get",
		"GET",
		"/api/v1/admin/users/{userId}",
		copy(
			"Get user details",
			"Returns roles, providers, lockout, and active sessions.",
			"Benutzerdetails abrufen",
			"Liefert Rollen, Provider, Lockout und aktive Sitzungen.",
			"Kullanıcı detayını getir",
			"Roller, bağlı provider'lar, lockout ve aktif oturumlarla tam görünüm.",
		),
		"admin",
		"admin",
		{ pathParams: [{ name: "userId", value: DEMO.user.id }] },
	),
	endpoint(
		"admin-user-update",
		"PATCH",
		"/api/v1/admin/users/{userId}",
		copy(
			"Update a user",
			"Patches display name, verification status, or lockout reset.",
			"Benutzer aktualisieren",
			"Ändert Anzeigename, Bestätigungsstatus oder Lockout-Reset.",
			"Kullanıcıyı güncelle",
			"Display name, doğrulama durumu veya lockout temizleme alanlarını patch eder.",
		),
		"admin",
		"admin",
		{
			pathParams: [{ name: "userId", value: DEMO.user.id }],
			body: {
				displayName: "Reviewed User",
				emailVerified: true,
				unlock: true,
			},
		},
	),
	endpoint(
		"admin-user-delete",
		"DELETE",
		"/api/v1/admin/users/{userId}",
		copy(
			"Delete a user",
			"Deletes the user and credentials while preserving the audit trail.",
			"Benutzer löschen",
			"Löscht Benutzer und Credentials, während der Audit-Trail erhalten bleibt.",
			"Kullanıcıyı sil",
			"Kullanıcıyı ve credential'larını siler; audit trail yaşamaya devam eder.",
		),
		"admin",
		"admin",
		{
			pathParams: [{ name: "userId", value: DEMO.user.id }],
			destructive: true,
		},
	),
	endpoint(
		"admin-role-grant",
		"POST",
		"/api/v1/admin/users/{userId}/roles",
		copy(
			"Grant a role",
			"Assigns a fixed role ID; it takes effect after the next token issue.",
			"Rolle vergeben",
			"Weist eine feste Rollen-ID zu; wirksam nach der nächsten Token-Ausgabe.",
			"Rol ver",
			"Sabit rol id'sini kullanıcıya atar; yeni token issuance sonrası etkili olur.",
		),
		"admin",
		"admin",
		{
			pathParams: [{ name: "userId", value: DEMO.user.id }],
			body: { roleId: DEMO.adminRoleId },
			destructive: true,
		},
	),
	endpoint(
		"admin-role-revoke",
		"DELETE",
		"/api/v1/admin/users/{userId}/roles/{roleId}",
		copy(
			"Revoke a role",
			"Removes the grant; it takes effect after the next token issue.",
			"Rolle widerrufen",
			"Entfernt die Zuweisung; wirksam nach der nächsten Token-Ausgabe.",
			"Rolü geri al",
			"Rol grant'ını kaldırır; yeni token issuance sonrası etkili olur.",
		),
		"admin",
		"admin",
		{
			pathParams: [
				{ name: "userId", value: DEMO.user.id },
				{ name: "roleId", value: DEMO.adminRoleId },
			],
			destructive: true,
		},
	),
	endpoint(
		"admin-sessions-revoke",
		"DELETE",
		"/api/v1/admin/users/{userId}/sessions",
		copy(
			"Revoke a user's sessions",
			"Revokes every active session for incident response.",
			"Benutzersitzungen widerrufen",
			"Widerruft für Incident Response alle aktiven Sitzungen des Benutzers.",
			"Kullanıcının oturumlarını kapat",
			"Incident response için hedef kullanıcının tüm aktif oturumlarını iptal eder.",
		),
		"admin",
		"admin",
		{
			pathParams: [{ name: "userId", value: DEMO.user.id }],
			destructive: true,
		},
	),
	endpoint(
		"admin-audit",
		"GET",
		"/api/v1/admin/audit-logs",
		copy(
			"Query the audit trail",
			"Returns fixture and runtime security events as a paginated result.",
			"Audit-Trail abfragen",
			"Liefert Fixture- und Laufzeit-Sicherheitsereignisse paginiert.",
			"Audit trail sorgula",
			"Hazır fixture kayıtlarını ve çalışma sırasında oluşan güvenlik olaylarını sayfalı döndürür.",
		),
		"admin",
		"admin",
		{
			query: [
				{ name: "page", value: "1" },
				{ name: "pageSize", value: "20" },
				{ name: "sort", value: "occurredAt:desc" },
				{ name: "userId", value: "" },
				{ name: "eventType", value: "" },
				{ name: "from", value: "" },
				{ name: "to", value: "" },
				{ name: "correlationId", value: "" },
			],
		},
	),
];

export const endpointById = (id: string): EndpointDefinition | undefined =>
	ENDPOINTS.find((item) => item.id === id);

export const endpointCopy = (
	item: EndpointDefinition,
	locale: AppLocale,
): LocalizedCopy => item.copy[locale];

export const normalizeLocale = (locale: string): AppLocale => {
	if (locale === "de" || locale === "tr") return locale;
	return "en";
};
